title: Jamie Adams
description: High-assurance Linux systems, logging, auditing, and tooling
theme: minima

# Ensure GitHub Pages compatibility
markdown: kramdown

# Do NOT set baseurl for a user site
baseurl: ""

# Optional but useful
show_excerpts: false

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
